apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            key: apiKey
            name: secrets-mgr-ap-key
            namespace: kube-system
      serviceUrl: >-
        https://c5a1a891-99e1-4f43-acf2-2167c16ed574.au-syd.secrets-manager.appdomain.cloud