{{- if .Values.existingSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openldap
  namespace: openldap
spec:
  data:
    - secretKey: adminPassword
      remoteRef:
        key: 98e4fb53-f17e-b92c-94c3-76f33160c3dc
    - secretKey: configPassword
      remoteRef:
        key: ee65c457-1344-b139-1095-660f29dee62b
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: openldap
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        LDAP_ADMIN_PASSWORD: |-
          {{ "{{ .adminPassword | toString }}" }}
        LDAP_CONFIG_PASSWORD: |-
          {{ "{{ .configPassword | toString }}" }}
{{- end }}