apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-bind-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: adminPassword
      remoteRef:
        key: 98e4fb53-f17e-b92c-94c3-76f33160c3dc
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ldap-bind-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ldapUsername: cn=admin,dc=cp
        ldapPassword: |-
          {{ .adminPassword | toString }}