apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resource-registry-admin-secret
  namespace: cp4ba
spec:
  data:
    - secretKey: universalPassword
      remoteRef:
        key: 9f114409-ae1d-4958-72a3-6cbe0d4759d7
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: resource-registry-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        rootPassword:  |-
          {{ .universalPassword | toString }}
        readUser: reader
        readPassword:  |-
          {{ .universalPassword | toString }}
        writeUser: writer
        writePassword:  |-
          {{ .universalPassword | toString }}